src/Entity/Card.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CardRepository::class)]
#[ORM\Table(name: '`cards`')]
class Card
{
    #[ORM\Id]
    #[ORM\Column(length: 255)]
    private ?string $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $supertype = null;

    /**
     * @var Collection<int, CardImage>|null
     */
    #[ORM\OneToMany(targetEntity: CardImage::class, mappedBy: 'card')]
    private ?Collection $images = null;

    /**
     * @var Collection<int, Type>|null
     */
    #[ORM\ManyToMany(targetEntity: Type::class, mappedBy: 'cards')]
    private ?Collection $types = null;

    /**
     * @var Collection<int, PokemonAttack>|null
     */
    #[ORM\OneToMany(targetEntity: PokemonAttack::class, mappedBy: 'card')]
    private ?Collection $attacks = null;

    /**
     * @var Collection<int, PokemonWeakness>|null
     */
    #[ORM\ManyToMany(targetEntity: PokemonWeakness::class, mappedBy: 'cards')]
    private ?Collection $weaknesses = null;

    /**
     * @var Collection<int, PokemonResistance>|null
     */
    #[ORM\ManyToMany(targetEntity: PokemonResistance::class, mappedBy: 'cards')]
    private ?Collection $resistances = null;

    #[ORM\ManyToOne(targetEntity: Set::class, inversedBy: 'cards')]
    private ?Set $set = null;

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setId(string $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSupertype(): ?string
    {
        return $this->supertype;
    }

    public function setSupertype(string $supertype): static
    {
        $this->supertype = $supertype;

        return $this;
    }

    /**
     * @return Collection<int, CardImage>|null
     */
    public function getImages(): ?Collection
    {
        return $this->images;
    }

    public function addImage(CardImage $image): static
    {
        if (is_null($this->images)) {
            $this->images = new ArrayCollection();
        }
        $this->images->add($image);

        return $this;
    }

    public function getSmallImage(): ?CardImage
    {
        return $this->getImage('small');
    }

    public function getLargeImage(): ?CardImage
    {
        return $this->getImage('large');
    }

    public function getImage(string $type): ?CardImage
    {
        if (!is_null($this->images)) {
            /** CardImage $image */
            foreach ($this->images as $image) {
                if ($image->getType() === $type) {
                    return $image;
                }
            }
        }

        return null;
    }

    /**
     * @return Collection<int, Type>|null
     */
    public function getTypes(): ?Collection
    {
        return $this->types;
    }

    public function addType(Type $type): static
    {
        if (is_null($this->types)) {
            $this->types = new ArrayCollection();
        }
        $this->types->add($type);

        return $this;
    }

    public function checkType(Type $type): bool
    {
        if (is_null($this->types)
            || $this->types->isEmpty()
        ) {
            return false;
        }

        return array_any($this->types->toArray(), fn ($cardType): bool => $type->getName() === $cardType->getName());
    }

    /**
     * @return Collection<int, PokemonAttack>|null
     */
    public function getAttacks(): ?Collection
    {
        return $this->attacks;
    }

    /**
     * @return $this
     */
    public function addAttack(PokemonAttack $pokemonAttack): static
    {
        if (is_null($this->attacks)) {
            $this->attacks = new ArrayCollection();
        }
        $this->attacks->add($pokemonAttack);

        return $this;
    }

    /**
     * @return Collection<int, PokemonWeakness>|null
     */
    public function getWeaknesses(): ?Collection
    {
        return $this->weaknesses;
    }

    public function addWeakness(PokemonWeakness $pokemonWeakness): static
    {
        if (is_null($this->weaknesses)) {
            $this->weaknesses = new ArrayCollection();
        }
        $this->weaknesses->add($pokemonWeakness);

        return $this;
    }

    /**
     * @return Collection<int, PokemonResistance>|null
     */
    public function getResistances(): ?Collection
    {
        return $this->resistances;
    }

    public function addResistance(PokemonResistance $pokemonResistance): static
    {
        if (is_null($this->resistances)) {
            $this->resistances = new ArrayCollection();
        }
        $this->resistances->add($pokemonResistance);

        return $this;
    }

    public function getSet(): ?Set
    {
        return $this->set;
    }

    public function setSet(?Set $set): static
    {
        $this->set = $set;

        return $this;
    }
}

src/Controller/CardsController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Card;
use App\Repository\CardRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class CardsController extends AbstractController
{
    public const int MAX_RESULTS = 20;

    #[Route('/cards', name: 'cards_index')]
    public function index(CardRepository $cardRepository, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);
        $cards = $cardRepository->paginateCards($page, self::MAX_RESULTS);
        $maxPages = ceil($cards->getTotalItemCount() / self::MAX_RESULTS);

        return $this->render('cards/index.html.twig', ['page' => $page, 'cards' => $cards, 'maxPages' => $maxPages]);
    }

    #[Route('/cards/{card}', name: 'cards_show')]
    public function show(Card $card, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);

        return $this->render('cards/show.html.twig', ['card' => $card, 'page' => $page]);
    }
}

templates/cards/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Welcome to Pokemon TCG Portal!</h1>

    <table>
        <thead>
            <tr>
                <th>Imagem da carta</th>
                <th>Nome do Pokémon</th>
                <th>ID do Pokémon</th>
                <th>Tipo(s)</th>
            </tr>
        </thead>
        <tbody>
            {% for card in cards %}
                <tr>
                    <td>
                        {% if page is defined and page is not empty and page > 1 %}
                            <a href="{{ path('cards_show', {'card': card.id, 'page': page}) }}"><img src="{{ card.smallImage.url }}" alt=""/></a>
                        {% else %}
                            <a href="{{ path('cards_show', {'card': card.id}) }}"><img src="{{ card.smallImage.url }}" alt=""/></a>
                        {% endif %}
                    </td>
                    <td>{{ card.name }}</td>
                    <td>{{ card.id }}</td>
                    <td>
                        {% for type in card.types %}
                            {{ type.name }} <br>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {{ knp_pagination_render(cards) }}

{% endblock %}

templates/cards/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Detalhes da Carta</h1>

    <table>
        <tbody>
            <tr>
                <th>Imagem em alta definição</th>
                <td><img src="{{ card.largeImage.url }}" alt=""/></td>
            </tr>
            <tr>
                <th>Nome</th>
                <td>{{ card.name }}</td>
            </tr>
            <tr>
                <th>ID do Pokémon</th>
                <td>{{ card.id }}</td>
            </tr>
            <tr>
                <th>Tipo(s)</th>
                <td>
                    {% for type in card.types %}
                        {{ type.name }} <br>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Resistência(s)</th>
                <td>
                    {% for resistance in card.resistances %}
                        {{ resistance.type.name }} {{ resistance.value }} <br>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Fraqueza(s)</th>
                <td>
                    {% for weakness in card.weaknesses %}
                        {{ weakness.type.name }} {{ weakness.value }} <br>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Lista de nomes dos ataques do Pokémon</th>
                <td>
                    {% for attack in card.attacks %}
                        {{ attack.name }} <br>
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>

    {% if page is defined and page is not empty and page > 1 %}
        <a href="{{ path('cards_index', {'page': page}) }}">Voltar</a>
    {% else %}
        <a href="{{ path('cards_index') }}">Voltar</a>
    {% endif %}
{% endblock %}